version: '3'
services:
  backend:
    build: ./
    image: robertcsapo/cisco-dnac-network-devices-cfg-backup-s3
    environment:
     - DNAC_HOST=dnac.example.tld
     - DNAC_USER=user
     - DNAC_PASS=password
     - DNAC_SSL_VERIFY=False
     - STORAGE=MINIO
     - S3BUCKET=cisco-dnac-network-devices-cfg-backup-s3
     - AWS_ACCESS_KEY=minioadmin
     - AWS_SECRET_KEY=minioadmin
     - ENDPOINT_URL=http://<URL-MINIO>:9000/
    network_mode: bridge
